### ISSUE TITLE
License quote question

### ISSUE THREAD

**Issue by commjoen** [dalibo/pandocker#145]
Hi there!
As we are working our way with the MASVS project from OWASP to use your container for PDF generation, I wonder: what type of notion do we need to include in our dockerfile and/or documentation that we are using your container as a base container?

**Comment by daamien** [comment]
Hi @commjoen,

It depends on what you intend to distribute. 

* If your goal is to redistribute only the PDF files, then they are only artifacts of the pandocker image and there are not covered by the pandocker licence. In my view, having  a section in your documents that describes your document production toolchain is a nice thing, but it's not mandatory. 

* If you want to redistribute the pandocker image in itself, then it different. For example, you may want external contributors to be able to build the PDF files by themselfes, or you want to embed the document production toolchain inside the document so that people can still build the files in 10-20 years, etc. In this case, you are distributing the pandocker image in itself and you have to respect the BSD licence.... which basically means you just have to add the link below in the README file of your project or wherever you feel it's appropriate.

  https://github.com/dalibo/pandocker/blob/latest/LICENSE
